name: QA

on:
  workflow_call: ~

jobs:

  run-tests:
    name: Test PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
    runs-on: [self-hosted, alpha]
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
        symfony: [ '5.4.*', '6.2.*', '6.3.*', '6.4.*' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex
        env:
          runner: self-hosted
      - name: Download dependencies
        uses: ramsey/composer-install@v2
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: ./vendor/bin/phpunit
